travis:
  secure:
    BINSTAR_TOKEN: QyPdKudMHUenzitb1+bCObpJjNHd8bP5kyK3Ofhm6I+sEIB2emz4IHLPPuF759+p77LcIiNimiHoIO+fRC5UxP/vEghusyTirrfKr/JPiDUPkFBodJiF4OOg2JzAvUo1K2R5sIlDY9j18sCXb4FOMncL4Gkf7MI0Vu1eHwrZqV+N5KXct04S8BE1sWdac1I6xgXEQp4cQIYQDbR8KT5k2+a/ulc8VVVdUVudzOkGnWdaWiSW5+2j7ZFZCfQOiw97zLiqkyu9yUMhYLfxPdND6x2TcG68Bux20V/yuNbiFPvXVBzuJGT+PcyITvfMElOurv29tSq4YPnbz24LpEDPrD0Arp3ujbBY4i0mOIuRt65DjJplPjtpuxqoCZjxlzQ8cSqRAq1bZVSrtCjQ9qWAxaSt/gj7JIxskM/bo/QCl7mAS3JgokJ2g4jfNAASIqOQRbTIHWfKsAx9LexdoNuh3tynHV1Ee5riGe3/4/fYQt7iVpXb0xYqacvhS7dxibwJdS1PHsbTBSPXGlZ5vg9Jtj0Hq1Nv6E7oOpj5XBQaED8qyzkTu5MHfXgEK5ztsypgMMYhd92yUdbGfHk5r5DHHXEgpErPZ94z1V1fHTbj5TNVs1twf2tYduDplHKBHw7VYIyN6pzWKnzjmsoYwPyO1zPacFwYMucxRXvMqyvpeX4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
